
services:
  - type: web
    name: frontend
    env: node
    buildCommand: npm run build
    startCommand: npm start
    rootDir: frontend

  - type: web
    name: backend
    env: node
    buildCommand: npm run build
    startCommand: npm start
    rootDir: backend
